export const posts=[
{slug:'how-to-create-a-qr-code-for-a-website',title:'How to Create a QR Code for a Website',category:'How-to',date:'2026-09-25',reading:'4 min',excerpt:'A practical guide to turning a website address into a QR code for print and digital use.',body:[['Start with the complete URL','Use the full HTTPS address you want people to visit. Check that it works on a phone before generating the code.'],['Create and test','Open the URL QR Code Generator, enter the address, review the preview, and scan the downloaded file.'],['Use the right size','A printed QR code needs enough physical size and contrast for the intended scanning distance. Keep a clear margin around it.']]},
{slug:'how-to-create-a-wifi-qr-code',title:'How to Create a WiFi QR Code',category:'How-to',date:'2026-09-25',reading:'4 min',excerpt:'Make guest WiFi access simpler with a QR code containing the network connection details.',body:[['Collect the network details','You need the WiFi network name, security type, and password. A hidden-network setting may also be relevant.'],['Generate the code','Use the WiFi QR Code Generator and check the result with a phone connected to cellular data or another network.'],['Protect the printout','Because the code can contain the network password, place it where only intended guests can access it.']]},
{slug:'how-to-create-a-whatsapp-qr-code',title:'How to Create a QR Code for WhatsApp',category:'How-to',date:'2026-09-25',reading:'3 min',excerpt:'Create a scannable link that opens a WhatsApp conversation from a phone.',body:[['Use a public chat URL','Prepare the WhatsApp URL you want customers to open. Verify the number and optional message first.'],['Generate the QR code','Paste the URL into the WhatsApp QR Code Generator and download the result.'],['Test before printing','Scan from the same type of phone your audience will use and confirm the correct conversation opens.']]},
{slug:'how-to-create-a-qr-code-for-a-business-card',title:'How to Create a QR Code for a Business Card',category:'Business',date:'2026-09-25',reading:'4 min',excerpt:'Add a QR code to a business card to make websites and contact details easier to reach.',body:[['Choose the destination','You can use a website, vCard contact details, booking page, or professional social profile.'],['Keep the code readable','Leave sufficient quiet zone around the QR code and use strong contrast against the card.'],['Print-test the card','Scan a physical proof before ordering a large print run.']]},
{slug:'how-restaurants-can-use-qr-codes',title:'How Restaurants Can Use QR Codes',category:'Business',date:'2026-09-25',reading:'5 min',excerpt:'Ideas for menus, ordering, reservations, maps, feedback, and promotions.',body:[['Digital menus','Link table signage to a mobile-friendly menu that loads quickly.'],['Ordering and reservations','Use QR codes for an ordering page or reservation flow, but make sure the destination remains current.'],['Feedback and information','QR codes can also point to maps, contact details, opening hours, or a feedback form.']]},
{slug:'how-to-create-a-qr-code-for-a-pdf',title:'How to Create a QR Code for a PDF',category:'How-to',date:'2026-09-25',reading:'4 min',excerpt:'Point a QR code to a public PDF without uploading the file to the generator.',body:[['Host the PDF','Use a stable public URL that people can access from their phones.'],['Generate the code','Paste the PDF URL into the PDF QR Code Generator and download the QR code.'],['Check the destination','Test the exact link on a mobile device and confirm permissions allow the intended audience to view the PDF.']]},
{slug:'how-to-create-a-qr-code-for-a-youtube-video',title:'How to Create a QR Code for a YouTube Video',category:'How-to',date:'2026-09-25',reading:'3 min',excerpt:'Turn a YouTube video URL into a QR code for posters, classrooms, events, and displays.',body:[['Copy the video URL','Use the share URL for the video and make sure it is the correct video.'],['Generate and download','Use the YouTube QR Code Generator and choose a suitable export format.'],['Test on mobile','Scan the final code and confirm the video opens at the expected destination.']]},
{slug:'how-to-create-a-qr-code-for-social-media',title:'How to Create a QR Code for Social Media',category:'How-to',date:'2026-09-25',reading:'4 min',excerpt:'Use QR codes to connect printed materials to public social profiles and pages.',body:[['Choose one stable profile','A single public profile or landing page is easier to maintain than many separate codes.'],['Generate the code','Paste the public social URL into the Social Media QR Code Generator.'],['Plan for change','If your profile URL changes, a static QR code will not automatically update. Test it periodically.']]},
{slug:'how-qr-codes-work',title:'How QR Codes Work',category:'Guide',date:'2026-09-25',reading:'6 min',excerpt:'Understand the basics of QR encoding, error correction, quiet zones, and scanning.',body:[['Encoding information','QR codes represent information as a structured grid of dark and light modules.'],['Error correction','QR standards include error-correction levels that can recover from some missing or damaged modules.'],['Scanning conditions','Contrast, size, focus, lighting, and a clear margin all affect practical scanning reliability.']]},
{slug:'static-vs-dynamic-qr-codes',title:'Static vs Dynamic QR Codes',category:'Guide',date:'2026-09-25',reading:'5 min',excerpt:'Understand the practical difference between codes that encode a destination directly and redirecting systems.',body:[['Static QR codes','A static code directly contains its data. If the encoded URL changes, the printed QR code itself does not change.'],['Dynamic QR systems','A dynamic system usually encodes a short redirect controlled by a service, allowing the destination to change and often adding analytics.'],['Choosing a model','For simple permanent links, static codes can be straightforward. Dynamic services add infrastructure and may involve accounts or fees.']]},
{slug:'qr-code-ideas-for-small-businesses',title:'QR Code Ideas for Small Businesses',category:'Business',date:'2026-09-25',reading:'5 min',excerpt:'Practical ways small businesses can connect physical materials with digital information.',body:[['Business cards','Link to a website, contact card, booking page, or map.'],['Printed promotions','Connect flyers and posters to campaign landing pages or product information.'],['In-store information','Use codes for menus, instructions, catalogs, support information, or feedback.']]},
{slug:'how-to-use-qr-codes-on-flyers-and-posters',title:'How to Use QR Codes on Flyers and Posters',category:'Design',date:'2026-09-25',reading:'5 min',excerpt:'Placement, contrast, size, calls to action, and testing tips for printed QR codes.',body:[['Give the code a job','Tell readers what they get by scanning: menu, booking, map, video, offer, or contact details.'],['Protect readability','Avoid busy backgrounds behind the code and keep a clear quiet zone.'],['Test the real print','A QR code that scans on a large monitor may behave differently after printing. Test the final material.']]}
];
