export type ToolKey='url'|'text'|'email'|'phone'|'sms'|'wifi'|'vcard'|'location'|'event'|'pdf'|'youtube'|'social'|'payment'|'multi'|'business'|'restaurant'|'whatsapp';
export const toolData:Record<ToolKey,{slug:string;name:string;title:string;description:string}>={
url:{slug:'url-to-qr-code',name:'URL',title:'URL to QR Code Generator – Create QR Codes Free | Free QR Code Studio',description:'Turn any website address into a downloadable QR code in seconds. Free, browser-based, and no sign up required.'},
text:{slug:'text-to-qr-code',name:'Text',title:'Text to QR Code Generator – Create Free QR Codes | Free QR Code Studio',description:'Convert plain text into a QR code and download it as PNG or SVG. No account required.'},
email:{slug:'email-qr-code',name:'Email',title:'Email QR Code Generator – Create Email QR Codes Free | Free QR Code Studio',description:'Create a QR code that opens an email with an address, subject, and message already prepared.'},
phone:{slug:'phone-number-qr-code',name:'Phone',title:'Phone Number QR Code Generator – Create QR Codes Free | Free QR Code Studio',description:'Create a QR code for a phone number so people can quickly open a call action on their device.'},
sms:{slug:'sms-qr-code',name:'SMS',title:'SMS QR Code Generator – Create SMS QR Codes Free | Free QR Code Studio',description:'Generate an SMS QR code with a phone number and message, ready to scan from a mobile device.'},
wifi:{slug:'wifi-qr-code',name:'WiFi',title:'WiFi QR Code Generator – Create WiFi QR Codes Free | Free QR Code Studio',description:'Create a WiFi QR code for guests with network name, password, security type, and hidden-network support.'},
vcard:{slug:'vcard-qr-code',name:'vCard',title:'vCard QR Code Generator – Create Digital Contact QR Codes Free | Free QR Code Studio',description:'Turn business contact details into a scannable vCard QR code for easy sharing.'},
location:{slug:'location-qr-code',name:'Location',title:'Location QR Code Generator – Create Location QR Codes Free | Free QR Code Studio',description:'Create a QR code that opens a map location from latitude and longitude.'},
event:{slug:'event-qr-code',name:'Event',title:'Event QR Code Generator – Create Event QR Codes Free | Free QR Code Studio',description:'Create QR codes for events with title, date, time, location, and description.'},
pdf:{slug:'pdf-qr-code',name:'PDF',title:'PDF QR Code Generator – Create PDF QR Codes Free | Free QR Code Studio',description:'Create a QR code for a publicly accessible PDF URL and share it on print or digital materials.'},
youtube:{slug:'youtube-qr-code',name:'YouTube',title:'YouTube QR Code Generator – Create QR Codes Free | Free QR Code Studio',description:'Turn a YouTube video URL into a downloadable QR code for posters, classrooms, events, and more.'},
social:{slug:'social-media-qr-code',name:'Social Media',title:'Social Media QR Code Generator – Create QR Codes Free | Free QR Code Studio',description:'Create a QR code for any social profile or public social URL without an account.'},
payment:{slug:'payment-qr-code',name:'Payment',title:'Payment QR Code Generator – Create Payment Link QR Codes Free | Free QR Code Studio',description:'Create a QR code from a payment or checkout URL. The tool does not process payments itself.'},
multi:{slug:'multi-url-qr-code',name:'Multi-URL',title:'Multi-URL QR Code Generator – Create QR Codes Free | Free QR Code Studio',description:'Create a QR code from a list of URLs. Version 1 encodes the supplied links as text for reliable scanning.'},
business:{slug:'business-qr-code',name:'Business',title:'Business QR Code Generator – Create QR Codes Free | Free QR Code Studio',description:'Create a business QR code for your website, contact details, location, social profile, or public link.'},
restaurant:{slug:'restaurant-qr-code',name:'Restaurant',title:'Restaurant QR Code Generator – Create Menu QR Codes Free | Free QR Code Studio',description:'Create a QR code for a restaurant menu, ordering page, booking page, or other public URL.'},
whatsapp:{slug:'whatsapp-qr-code',name:'WhatsApp',title:'WhatsApp QR Code Generator – Create QR Codes Free | Free QR Code Studio',description:'Create a QR code for a WhatsApp chat link so customers can start a conversation quickly.'}
};
export const tools=Object.entries(toolData).map(([key,v])=>({key:key as ToolKey,...v}));
